### ISSUE TITLE
[#0007] Documentação Sprint 1 (ReadMe)

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-documentation#3]
Readme [sprint 01](https://github.com/The-Bugger-Ducks/mood-hound-documentation/tree/sprint-01):

- [x] Editar descrição da sprint
- [x] Adicionar imagem do burndown
- [ ] Adicionar GIFs
- [x] Corrigir o link e o clicável para o repositório de nlp (está "_mood-hound-nlpk_")
- [x] Adicionar descrição das atividades desenvolvidas nessa sprint

**Comment by MariaGabrielaReis** [comment]
~~Alterar no readme principal na descrição "lingaem" pra "linguagem"~~

**Comment by drisabelles** [comment]
**Readme principal:** ~~Adicionar (provavelmente) novas imagens dos backlogs e a imagem faltante das user stories~~
